domains:
  - name: .example.com
    records:
      - type: A
        value: 172.2.2.1
      - type: A
        value: 172.2.2.2
      - type: AAAA
        value: 2800:03f0:4002:0813:0000:0000:0000:200e
      - type: AAAA
        value: 2800:03f0:4002:0813:0000:0000:0000:200f
      - type: MX
        value: 20 .mx.example.com
      - type: MX
        value: 25 .mxb.example.com
  - name: .mx.example.com
    records:
      - type: A
        value: 172.2.2.3
  - name: .example.com.ar
    records:
      - type: A
        value: 172.3.2.1
  - name: .google.com.ar
    records:
      - type: A
        value: 172.2.2.1
      - type: A
        value: 172.2.2.2
      - type: AAAA
        value: 2800:03f0:4002:0813:0000:0000:0000:200e
      - type: AAAA
        value: 2800:03f0:4002:0813:0000:0000:0000:200f
      - type: MX
        value: 20 .mx.example.com
