domains:
  - name: .google.com
    records:
      - type: A
        value: 127.0.0.1
        ttl: 300
      - type: A
        value: 127.0.0.2
        ttl: 300
  - name: .facebook.com
    records:
      - type: A
        value: 127.1.0.1
        ttl: 300
